# Generated by Django 4.1.3 on 2022-11-07 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroResidencia', models.IntegerField()),
                ('nombre_dueño', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('Entregado', 'Entregado'), ('Pendiente', 'Pendiente')], max_length=30)),
                ('residencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.residencia')),
            ],
        ),
    ]
